parcial/Controllers/EnterprisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UNFV.Portfolio.Models;

namespace UNFV.Portfolio.Controllers
{
    public class EnterprisesController : Controller
    {
        private UNFVPortfolioContext db = new UNFVPortfolioContext();

        // GET: Enterprises
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        // GET: Enterprises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enterprise enterprise = db.Clients.Find(id);
            if (enterprise == null)
            {
                return HttpNotFound();
            }
            return View(enterprise);
        }

        // GET: Enterprises/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Enterprises/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnterpriseID,Name,URL,Logo")] Enterprise enterprise)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(enterprise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(enterprise);
        }

        // GET: Enterprises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enterprise enterprise = db.Clients.Find(id);
            if (enterprise == null)
            {
                return HttpNotFound();
            }
            return View(enterprise);
        }

        // POST: Enterprises/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnterpriseID,Name,URL,Logo")] Enterprise enterprise)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enterprise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enterprise);
        }

        // GET: Enterprises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enterprise enterprise = db.Clients.Find(id);
            if (enterprise == null)
            {
                return HttpNotFound();
            }
            return View(enterprise);
        }

        // POST: Enterprises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enterprise enterprise = db.Clients.Find(id);
            db.Clients.Remove(enterprise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

parcial/Controllers/UploadsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UNFV.Portfolio.Controllers
{
    public class UploadsController : Controller
    {
        //POST: Uploads/UploadImages
        [HttpPost]
        public ActionResult UploadImages()
        {
            try
            {
                string filename = "";
                foreach (string upload in Request.Files)
                {
                    if (Request.Files[upload].FileName != "")
                    {
                        string path = AppDomain.CurrentDomain.BaseDirectory + "/Images/";
                        filename = Path.GetFileName(Request.Files[upload].FileName);
                        Request.Files[upload].SaveAs(Path.Combine(path, filename));
                    }
                }

                return Json(filename, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

parcial/Views/Enterprises/Create.cshtml
@model UNFV.Portfolio.Models.Enterprise

@Html.Hidden("UrlUploadFiles", Url.Action("UploadImages", "Uploads"))

@{
    ViewBag.Title = "Crear Institucion";
    ViewBag.Message = "Vamos a crear una Institucion";

}

<div class="section" id="enterprises">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 page-header">
                <h4 class="heading">@ViewBag.Title</h4>
                <p>@ViewBag.Message</p>
            </div>
            <div class="col-sm-12 col-md-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Enterprise</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="file" id="UploadImage">
                                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control UploadImage" } })
                                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/uploads")
}

parcial/Views/Enterprises/Delete.cshtml
@model UNFV.Portfolio.Models.Enterprise

@{
    ViewBag.Title = "Delete";
}

@{
    ViewBag.Title = "Eliminar Empresa";
    ViewBag.Message = "Seguro de querer hacer esto?";

}

<div class="section" id="enterprises">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 page-header">
                <h4 class="heading">@ViewBag.Title</h4>
                <p>@ViewBag.Message</p>
            </div>
            <div class="col-sm-12 col-md-12">
                <div>
                    <h4>Empresa</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.URL)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.URL)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Logo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Logo)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


parcial/Views/Enterprises/Details.cshtml
@model UNFV.Portfolio.Models.Enterprise

@{
    ViewBag.Title = "Detalle de Empresa";
    ViewBag.Message = "Viendo un detalle de una empresa";

}

<div class="section" id="enterprises">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 page-header">
                <h4 class="heading">@ViewBag.Title</h4>
                <p>@ViewBag.Message</p>
            </div>
            <div class="col-sm-12 col-md-12">
                <div>
                    <h4>Enterprise</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.URL)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.URL)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Logo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Logo)
                        </dd>

                    </dl>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.EnterpriseID }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>
        </div>
    </div>
</div>




parcial/Views/Enterprises/Edit.cshtml
@model UNFV.Portfolio.Models.Enterprise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enterprise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EnterpriseID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

parcial/Views/Enterprises/Index.cshtml
@model IEnumerable<UNFV.Portfolio.Models.Enterprise>

@{
    ViewBag.Title = "Clientes";
    ViewBag.Message = "Confian en mi";

}

@section Styles {
    @Styles.Render("~/Content/lightbox_css")
}

<div class="section" id="enterprises">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 page-header">
                <h4 class="heading">@ViewBag.Title</h4>
                <p>@ViewBag.Message</p>
            </div>
            @foreach (var item in Model)
            {
                <div class="col-sm-6 col-lg-3 col-md-6 col-xs-12">
                    <div class="thumbnail">
                        <a href="../Images/@Html.DisplayFor(modelItem => item.Logo)" class="thumbnail" data-lightbox="enterprises" data-title="@Html.DisplayFor(modelItem => item.Name)"><img src="../Images/@Html.DisplayFor(modelItem => item.Logo)" alt="@Html.DisplayFor(modelItem => item.Name)"></a>
                        <div class="caption">
                            <h3><a href='@Url.Action("Details", new { id = item.EnterpriseID })'>@Html.DisplayFor(modelItem => item.Name)</a></h3>
                            <p>@Html.DisplayFor(modelItem => item.URL)</p>
                            <p>
                                <small>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.EnterpriseID }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.EnterpriseID })
                                </small>
                            </p>
                        </div>
                    </div>
                </div>
            }
            @*<div class="col-sm-12 col-md-12">
                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.URL)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Logo)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.URL)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Logo)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.EnterpriseID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.EnterpriseID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.EnterpriseID })
                            </td>
                        </tr>
                    }

                </table>
            </div>*@
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/lightbox_js")
}